<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3CirXST\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3CirXST/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3CirXST.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3CirXST\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3CirXST\App_KernelDevDebugContainer([
    'container.build_hash' => '3CirXST',
    'container.build_id' => '0b3557a5',
    'container.build_time' => 1638751797,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3CirXST');
